//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isrpo_lab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pr4_PolyakovEntities : DbContext
    {
        public static pr4_PolyakovEntities _context;
        public static pr4_PolyakovEntities GetContext()
        {
            if (_context == null) _context = new pr4_PolyakovEntities();
            return _context;
        }
        public pr4_PolyakovEntities()
            : base("name=pr4_PolyakovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<СекретныйВопрос> СекретныйВопрос { get; set; }
    }
}
