//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isrpo_lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string ЭлектронныйАдрес { get; set; }
        public string Пароль { get; set; }
        public string КодовоеСлово { get; set; }
        public string ОтветНаСекретныйВопрос { get; set; }
        public Nullable<int> КодСекретногоВопроса { get; set; }
        public int КодПользователя { get; set; }
    
        public virtual СекретныйВопрос СекретныйВопрос { get; set; }
    }
}
